#!/bin/bash

# sources
source ~/.bash_aliases

xsetroot -cursor_name xcapy
sxhkd &
bash ~/.config/polybar/launch.sh --cuts &
dunst &
ibus-daemon -rxRd &

bspc config border_width 2
bspc config window_gap 0

bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config focused_border_color "#43a047"

bspc config automatic_scheme longest_side

# wallpaper
feh --bg-scale ~/.config/wallpaper.png

# virtual desktops
bspc monitor -d 1 2 3 4 5

# duplicate screen
xrandr --output HDMI-1 --same-as eDP-1 --auto --scale-from 1920x1200
#bspc monitor eDP-1 -d 1 2 3 4 5
